### ISSUE TITLE
프로젝트 주제 선정

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#1]
```
Beyond-SW-camp first player
_           _         _
| | __ _ ___| |_    __| | __ _ _ __   ___ ___
| |/ _` / __| __|  / _` |/ _` | '_ \ / __/ _ \
| | (_| \__ \ |_  | (_| | (_| | | | | (_|  __/
|_|\__,_|___/\__|  \__,_|\__,_|_| |_|\___\___|

```

## 팀 배정이 확정되었습니다.
- README.md 확인 부탁드립니다.
- 29일 점심을 함께 하시며 ~ 팀별로 주제 1,2,3 순위를 의논 점심시간 끝나고 아래 코맨트로 올려주세요. 주제 확정은 당일 퇴근 전까지 공지 드리겠습니다.

**Comment by minu1215** [comment]
1. 효과적인 HR를 위한 인사 관리 시스템
2. 효율적인 업무를 위한 일정 관리 시스템
3. 최적의 영업을 위한 영업 관리 시스템

**Comment by ae-chae** [comment]
1. 공급망 관리를 위한 주문 관리 시스템
2. 최적의 영업을 위한 영업 관리 시스템
3. 효과적인 HR를 위한 인사 관리 시스템

**Comment by ldh0308** [comment]
1. 효과적인 HR를 위한 인사 관리 시스템
2. 공급망 관리를 위한 주문 관리 시스템
3. 효율적인 업무를 위한 일정 관리 시스템

**Comment by choi3179** [comment]
### [2팀] 고라희,김단아,우지영,최원규	
1. 효율적인 업무를 위한 일정 관리 시스템
2. 최적의 영업을 위한 영업 관리 시스템
3. 효과적인 HR를 위한 인사 관리 시스템

**Comment by pySatellite** [comment]
# 확정
team #2 효율적인 업무를 위한 일정 관리 시스템
team #4 공급망 관리를 위한 주문 관리 시스템
