### ISSUE TITLE
[T5] 화면설계서 제출합니다.

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#100]
- figma 를 활용하여 화면설계서 작성을 진행하였습니다.
- 공용문서함에 PNG파일로 업데이트 하였으나 그림이 작아  figma링크도 같이 공유드립니다.
  - https://drive.google.com/file/d/1Ff7Pu8Lvfwq_rnYtAD-JgUy8EMQcujVT/view?usp=sharing
  - https://www.figma.com/file/e9mvmPw3RGB0uwmiNnBKkA/team-5?type=design&node-id=1669-162202&mode=design&t=QcwgDfGLXhATwgRp-0

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2qn1.png)
