### ISSUE TITLE
AWS Github Action Deploy 2 EC2

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#102]
# STEP 1
- [official  GitHub Actions – CI/CD pipeline to deploy a Web App to Amazon EC2](https://aws.amazon.com/ko/blogs/devops/integrating-with-github-actions-ci-cd-pipeline-to-deploy-a-web-app-to-amazon-ec2/)

----
![image](https://github.com/pySatellite/restdb/assets/87309910/95d780f2-2fa3-4c60-a82c-854945c57336)

# 그룹권한 추가 ( TL )
![image](https://github.com/pySatellite/restdb/assets/87309910/2c94c429-cf7a-4d86-b238-3468e7700736)

# 역할 생성 ( TL )
- action2ec2-deploy-role
![image](https://github.com/pySatellite/restdb/assets/87309910/9d8c0145-8f09-4f1c-8c9c-9ec6eec2bd00)
![image](https://github.com/pySatellite/restdb/assets/87309910/5772c98f-dc2e-402a-b18e-4ca20dc91b70)

- action2ec2-code-deploy-role
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/efc93a8a-1c44-47fa-9958-5c2bbfd7b121)
![image](https://github.com/pySatellite/restdb/assets/87309910/4c597801-f268-4812-8554-52d139c6efae)

# 역할 연결 -> EC2 ( TL )
![image](https://github.com/pySatellite/restdb/assets/87309910/8d174d28-6fb3-4efe-bccf-a72969a58232)

![image](https://github.com/pySatellite/restdb/assets/87309910/057ec3dc-767b-488a-8408-913195cd0ed2)

# 배포용 S3 Bucket 만들기 ( 각자 )
![image](https://github.com/pySatellite/restdb/assets/87309910/5460460d-555f-42b1-b3e0-99b44841fc54)

**Comment by pySatellite** [comment]
# CodeDeploy 애플리케이션 생성 (각자)
- mumbai-codedeploy-app
- AWS CodeDeploy → 애플리케이션 → 애플리케이션 생성
- 컴퓨팅 플랫폼은 EC2/온프레미스를 선택
![image](https://github.com/pySatellite/restdb/assets/87309910/de207637-c928-4f79-9bd2-3d52c0897b21)

# CodeDeploy 애플리케이션 - 배포그룹 생성 ( TL )
![image](https://github.com/pySatellite/restdb/assets/87309910/13e05813-ae01-4459-9fd7-6d44e5def32a)

![image](https://github.com/pySatellite/restdb/assets/87309910/d3308661-c0df-4936-8c46-0f0bded41286)

**Comment by pySatellite** [comment]
# GitHub Actions 가 사용자로 인증하기 위해 사용할 액세스 키를 생성(TL)
- 사용자 클릭 → 보안 자격 증명 → 액세스 키 → 액세스 키 만들기
- csv 다운로드 담당자에게 전달

![image](https://github.com/pySatellite/restdb/assets/87309910/777c425e-cdf3-4cbc-96ed-85e36c4fd779)

![image](https://github.com/pySatellite/restdb/assets/87309910/34075e33-39d4-49de-b1cd-e5c8e4fddf73)

# GitHub Repository Secrets 액세스 키 저장(각자)
- 위 전달 받은 CSV 참조
- Github Repository → Settings → Secrets and variables → Actions → New repository secret
- AWS_ACCESS_KEY_ID 생성
- AWS_SECRET_ACCESS_KEY 생성

![image](https://github.com/pySatellite/restdb/assets/87309910/7d6beebc-1331-4373-a2f1-c30388fa5a94)

**Comment by jsmin6330** [comment]
5팀은 TL도 사용자 계정 하나 생성합니다.
