### ISSUE TITLE
1차 dev deploy 제출 요청 ( 3/21 오전 )

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#103]
- [ ] 1. 초기 프로젝트 구조 설정 [PR URL]
- [ ] 2. local run test [PR COMMENT URL]
- [ ] 3. deploy aws ec2 url  [엔코아에서 만 접속 가능한 url, port 제출]
----

* 위 1,2,3 [URL] 을 아래 코맨트 제출 이후 체크
- [x] T1
- [ ] T2
- [ ] T3
- [ ] T4
- [ ] T5

**Comment by ldh0308** [comment]
-[ ] 1. 초기프로젝트 구성
- BE: https://github.com/9-1379/T3-R1-BE-Server/pull/11
- FE: https://github.com/9-1379/T3-R2-FE-Server/pull/5

-[ ] 2. local run test [PR COMMENT URL]

-[ ] 3. deploy aws ec2 url [엔코아에서 만 접속 가능한 url, port 제출]

**Comment by jsmin6330** [comment]
1. 초기 프로젝트 구조 설정 [PR URL]
    -
2. local run test [PR COMMENT URL]
    -
3. deploy aws ec2 url [엔코아에서 만 접속 가능한 url, port 제출]
    -

**Comment by CoffeerLatte** [comment]
- [ ] 1. 초기프로젝트 구성
- BE: https://github.com/team4-order/4team_final_MainSpring/pulls
- FE: https://github.com/team4-order/4team_final_MainVue/pulls ( 아직 미진행)

- [ ] 2. local run test [PR COMMENT URL]

- local run test는 아직 진행하지 않았습니다.  

- [ ] 3. deploy aws ec2 url [엔코아에서 만 접속 가능한 url, port 제출]

- 현재 db instance만 docker위에 올라가 있는 상태입니다.

```
Instance name : team4-order-db-ubuntu
- Public IPv4 DNS :  ec2-3-35-197-144.ap-northeast-2.compute.amazonaws.com
- Public IP = 3.35.197.144

```
DB Instance Inbound 규칙
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/125641153/c68e6827-ee1c-4f73-92bf-f86dadf51503)

**Comment by minu1215** [comment]
[x] 1. 초기 프로젝트 구조 설정 [PR URL]
- https://github.com/final-kms/main/pull/63
[x] 2. local run test [PR COMMENT URL]
- https://github.com/final-kms/main/pull/63#issuecomment-2010999849
[x] 3. deploy aws ec2 url [엔코아에서 만 접속 가능한 url, port 제출]
- http://ec2-13-125-164-232.ap-northeast-2.compute.amazonaws.com

**Comment by raheego** [comment]
1. 초기 프로젝트 구조 설정 [PR URL]
 - BE : 
 - FE : https://github.com/T2-Papillon/Main/issues/36
 3. local run test [PR COMMENT URL]
 - 확인중
 5. deploy aws ec2 url [엔코아에서 만 접속 가능한 url, port 제출]
 - 추후 추가 예정입니다.
