### ISSUE TITLE
[TEAM5] 클라우드 마리아DB 도커로 구축시 추가 데이터베이스 생성 방법 공유

### ISSUE THREAD

**Issue by jsmin6330** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#104]
저희 팀의 경우, 클라우드에 마리아DB 도커로 구축했는데,
HeidiSQL에서 기존에 있는 샘플 database 말고 database 생성이 안되서  고생하다가
방법을 찾아서 공유 드립니다.

- 상세: https://github.com/Team5-be01-Final-Project/.github/issues/41#issue-2191418997

원인: HeidiSQL 접속하는 기본 계정의 권한 문제

**Comment by pySatellite** [comment]
좋은 정보 공유 감사드립니다.

데이터베이스는 보안 이슈등으로 과거에 비해 패스워드 규칙도 복잡해지고 외부 접속등에 대해서도 보수적인 정책을 취하고 있습니다.

위 사항은 @jsmin6330 과 이야기 해보니 아래 설정으로 최초 Database 를 만들고 추가로 더 database 를 만들어야 하는 상황에서 권한 문제를 어떻게 해결한지 보여주시는 것으로 이해했습니다.

좋은 정보 감사드립니다.

- $ docker run --detach --name some-mariadb --env MARIADB_USER=example-user --env MARIADB_PASSWORD=my_cool_secret --env MARIADB_DATABASE=exmple-database --env MARIADB_ROOT_PASSWORD=my-secret-pw  mariadb:latest

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2qoe.png)
