### ISSUE TITLE
[T5] 시스템 아키텍처 제출합니다.

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#105]
- https://drive.google.com/drive/folders/1g18TOtVKlwjg4U4vY0wf-fvf6S4AEWyP

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/62015109/3e4a2c7f-dc62-4d1c-933f-0a13b983a7f0)

- v1 : 시스템 아키텍쳐 초기 버전
- v2 : 멘토링 진행 후 BE,FE,DB의 영역을 표시해주면 좋겠다고 하셔서 내용 추가

**Comment by pySatellite** [comment]
- 화려하군요 ^^
- 다만 해당 도식이 무엇을 중점으로 표현하는지가 중요한데요. 많은걸 넣어려 다보니 초점이 흐려지는 부분이 있습니다.
- 본 문서의 목적이 무엇일까요?
- 필요하면 회의를 잡아주세요.

**Comment by INAUGURATE-Ryong** [comment]
@pySatellite 
로컬에서 작업한 부분부터 표현을 하려다 보니 약간 과하게 짠 거 같습니다.
로컬 부분은 삭제하고 다시 작성하였습니다.

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/62015109/9949b4a3-5daf-455d-a6f4-57e72c8fa517)

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2qol.png)
