### ISSUE TITLE
wsl을 연결한 intellij가 생성한 프로젝트를 인식하지 못해 run이 불가하여 질문드립니다!

### ISSUE THREAD

**Issue by qkralsgml78** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#106]
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/149050285/77446a04-2a25-41b6-9294-71c2b12c87aa)
지금같이 계속 run이 활성화 되지 않아서
SDK는 wsl에 있는 java17로 설정을 하였고
wsl에 tomcat이 없는 문제인 줄 알고 tomcat을 깔아서 해봤지만 똑같은 상황입니다.
current file에도 wsl파일을 인식 시키려고 했지만 wsl환경이 뜨지 않아 해결하지 못했습니다.

모든 팀원들이 지금 같은 상황으로 해결되지 않고 있습니다.

**Comment by pySatellite** [comment]
관련해서 많은 문제점이 있고 wsl 과 최적화 되어 있지 않은 인상입니다.
- https://jjuniyo.tistory.com/2

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2qp6.png)
