### ISSUE TITLE
[T2][제출] 시스템 아키텍처 제출합니다. 

### ISSUE THREAD

**Issue by raheego** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#107]
공유 드라이브에 업로드 완료하였습니다.
확인 부탁드립니다.

### 링크
파일명 : [시스템 아키텍처_v1](https://docs.google.com/presentation/d/1PnRZ-t-cSKtpAjMINsELs8zEW9hCOFcReyN96Us9WJY/edit?usp=drive_link)

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/54056684/64c77bef-b26b-4bbc-b4f2-6225f09472c5)

위 문서는 초안버전으로 추후 수정 변경될 수 있다는 점 참고 부탁드립니다.

**Comment by pySatellite** [comment]
- 심플해서 좋아요.
- https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/109#issuecomment-2006590985 코맨트를 참조해서 프록시 캐싱 레이어를 두는 방안 및 STG 별로 다른 아키텍처를 구성하면 어떨까요?

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2qor.png)
