### ISSUE TITLE
[T4] 시스템 아키텍처 제출합니다.

### ISSUE THREAD

**Issue by qkralsgml78** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#109]
프로세스 명세서, 시스템 아키텍처 목록 등 포함된 ppt 링크로 제출합니다!
https://docs.google.com/presentation/d/1WSa1DHvJ0Ek7q0QIfEH7jFykyCtigH9Z/edit#slide=id.p1

**Comment by pySatellite** [comment]
- dev 에서는 개발 편의를 위해 local 과 같이 FE, BE 를 하나의 EC2 에 넣어 사용하시고 STG 이상에서 EC2 인스턴스를 나누어 보시면 어떨까요?
- STG 이상에서는 FE, BE 사이에 Proxy 캐시를 두는 것도 고려해 보면 좋겠습니다.
```mermaid
graph TD;
    USER-->FE;
    FE-->Proxy;
    Proxy-->BE-1;
    Proxy-->BE-2;
    Proxy-->BE-3;
    BE-1-->DB;
    BE-2-->DB;
    BE-3-->DB;
```

<img width="1228" alt="image" src="https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/7eaae3f4-f20d-4049-af2b-37ff91650343">

**Comment by pySatellite** [comment]
고용폴더 : https://drive.google.com/drive/folders/1bkpJdCsC9T-wmKTBs1zTtDdoDLILkqU7?usp=drive_link
