### ISSUE TITLE
[T1] 시스템 아키텍처 제출합니다. 

### ISSUE THREAD

**Issue by pdh4869** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#110]
[시스템 아키텍처](https://drive.google.com/drive/folders/1_r--Pm0LMddDNby5-QsCGXSiuIXRaot-)
 
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/76561901/b7087287-5cc8-4d6a-bc1a-f60189ce67e7)
* * *

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/76561901/1855a9ed-5225-450f-bcf2-b7b8b620527d)
* * *

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/76561901/7b127c40-3050-42ed-a1d4-ec4a3d7f002d)

**Comment by papercrane55123** [comment]
T1 SSG 시스템 아키텍처 제출합니다. 

### 특이사항
- DB를 나누는 과정(3번 슬라이드)에서 어떤 기준으로 MSA 형식으로 DB를 나누는 것이 좋을지 고민했습니다. 저희는 기능에 초점을 맞춰 DB를 분리했습니다. 선생님의 의견은 어떠신지 궁금합니다.
- Jenkins와 codeDeploy를 같이 사용해야할지, 젠킨스만 사용할지 고민했습니다. 검색을 통해 각각의 장점을 파악했고, 두가지 배포 도구를 모두 사용하는 것으로 의견이 모아졌으나, 선생님의 의견은 어떠신지 궁금합니다.
- 제작 버전은 v0.1과 v0.2로 나누었습니다. v0.2는 도전과제를 포함시킨 아키텍처입니다.

감사합니다.

**Comment by pySatellite** [comment]
@papercrane55123 회의를 잡아 주시면 의견 나누고 의견도 이곳에 공유하면 좋겠습니다.

질문 중 
- DB 분리 부분은 도식에 표현되지 않아 내용 파악이 어렵습니다. 회이 전에 간단히 답변 부탁드립니다.
- JENKINS 와 Action 을 모두 써보는 것은 필요 합니다. 다만 한꺼번에 쓰기 보다는 STG 별로 분리 하면 어떨까 싶어요. dev 는 Action STG 는 Jenkins ...

**Comment by papercrane55123** [comment]
@pySatellite 네 선생님! DB 분리는 아래와 같습니다. 기능을 기준으로 테이블 나누었습니다. 나누어진 테이블대로 서버 분리할 예정입니다.

![DB ERD v0 1 0 DB 분리](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/150432433/d5152246-99b1-4e82-9577-5f5bb04dd882)

회의는 2시 10분에서 40분까지로 잡아도 괜찮으실까요?

**Comment by pySatellite** [comment]
네 좋아요. 디비를 나누는 목적 및 이유가 궁금하네요. 회의에서 들어 보아요 ^^

**Comment by pySatellite** [comment]
- 특정 서비스 다운 시 서비스 동작 테스트 시나리오 및 정책이 있으면 좋겠네요.
- 모노로 이미 만든 시스템을 MSA 로 전환 하는 시도는 좋아 보입니다.

**Comment by papercrane55123** [comment]
@pySatellite 넵 오늘 피드백 주셔서 감사합니다! 회의록은 팀 레포 이슈에 정리해 두었습니다. 다른 팀이 필요하다면 후에 last-dance 이슈에도 올리도록 하겠습니다. 감사합니다.
https://github.com/final-kms/main/issues/60
