### ISSUE TITLE
[T2]ERD 제출합니다.

### ISSUE THREAD

**Issue by Afresh2** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#113]
![ERD](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/149090519/bb3198b5-211b-4962-8c42-44b73c0faa7e)

**Comment by pySatellite** [comment]
공용문서함 링크 부탁드립니다.

**Comment by raheego** [comment]
@pySatellite 
공용문서 링크 추가전달 드립니다.
 https://drive.google.com/file/d/1hkwXNEL79vJgCPwI1lKjIoSlvnwby-xN/view?usp=drive_link
 감사합니다.

**Comment by pySatellite** [comment]
확인했습니다.

![LGTM](https://i.lgtm.fun/2qol.png)
