### ISSUE TITLE
[T1] DB ERD v1.0 제출합니다.

### ISSUE THREAD

**Issue by papercrane55123** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#114]
[T1 ERD공용문서함](https://drive.google.com/drive/folders/17qISw1b61Znbj4Roq9G5TAHf_dLXgkpd)
![DB ERD v0 1 0](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/150432433/3de638b3-5350-4466-a7ed-278af2559aed)

### 특이사항
- 컬럼 명은 모두 유니크한 값을 갖도록 설정했습니다.
- 이외엔 금일 회의에서 진행한 내용과 동일합니다. 

감사합니다.

**Comment by pySatellite** [comment]
공용문서함 링크 추가 부탁드립니다. @papercrane55123

**Comment by papercrane55123** [comment]
@pySatellite [T1 ERD공용문서함](url) 입니다.

감사합니다.

**Comment by pySatellite** [comment]
감사합니다.

![LGTM](https://i.lgtm.fun/2qq8.png)
