### ISSUE TITLE
[T3] ERD-v1제출합니다.

### ISSUE THREAD

**Issue by Jaelinny** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#115]
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/1af1cf7d-f24b-4006-9677-c47d0f2f76d4)
- [ERD_링크](https://drive.google.com/drive/folders/1M7PLxPzVuI_EpSegAItHDasqoX4mc5mv)

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2qq8.png)
