### ISSUE TITLE
[T5] ERD-v6 제출합니다.

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#117]
![ERD v6](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/62015109/9dd7e899-f2b5-4587-a78b-a7f864a9f637)

**Comment by pySatellite** [comment]
@INAUGURATE-Ryong 문서 링크도 부탁드립니다.

**Comment by INAUGURATE-Ryong** [comment]
@pySatellite ERD링크 전달드립니다.
- https://drive.google.com/drive/folders/1j42FYsOK44UyDvBYGYrv1Q2gVxqoGcE9

**Comment by pySatellite** [comment]
오늘 휴가 아니던가요 ^^ 확인 했습니다.

![LGTM](https://i.lgtm.fun/2qol.png)
