### ISSUE TITLE
[T4] 주문 ERD v1.0.1 제출합니다.

### ISSUE THREAD

**Issue by qkralsgml78** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#118]
![주문 ERD v 1 0 1](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/149050285/8109a8b1-25d3-463d-9553-cd3efb363816)

- 링크 : https://drive.google.com/drive/folders/1-EwfmpeVPMJ2zyqvpjLUGzwLEuBE_MR-

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2qqk.png)
