### ISSUE TITLE
[3/22] AC 회의 - 초집중시간 운영

### ISSUE THREAD

**Issue by shimguh** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#120]
회의 내용
- 초집중시간 그대로 운영
- 16:00~16:50

**Comment by pySatellite** [comment]
우리 애자일 코치님들 쵝옵니다.

- 오늘 요기요라는 회사에서 애자일 코치는 다음과 같은 발표를 하고 있었네요.
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/b91e5aa9-d0fe-4077-9f4b-d0fa0c46160b)
