### ISSUE TITLE
[T5] AWS 배포시 COOKIE 관련 문제 질문

### ISSUE THREAD

**Issue by jsmin6330** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#124]
안녕하세요. 5팀 COOKIE 관련 이슈가 있어서 질문 드립니다.

1. 로컬호스트 (BE-FE)에서 로그인 성공 시 BE에서 쿠키를 생성해서 FE에게 전달, 사이트에서 쿠키를 잘 가지고 사용할 수 있습니다.

2. AWS 배포시 로그인 성공 시 BE에서 쿠키를 생성해서 FE에 전달까지는 확인, 하지만 경고와 함께 사이트에서 쿠키를 가지고 있지 않습니다.

- 네트워크 로그인 헤더 정보 이미지
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/150888333/e94866b8-0f27-4884-af78-5453c63a1d83)
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/150888333/be26ca59-44bd-4edb-91ac-4f7d12796e24)
- warning 내용

this attempt to set a cookie via a set-cookie header was blocked because its Domain attribute was invalid with regards to the current host url
set-cookie 헤더를 통해 쿠키를 설정하려는 시도는 현재 호스트 URL과 관련하여 해당 도메인 속성이 유효하지 않기 때문에 차단되었습니다.

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/150888333/0801ad2e-5e48-4217-af82-99e234f3c148)

### BE서버 쿠키 설정
```
 Cookie empCodeCookie = new Cookie("empCode", empCode.toString());
            empCodeCookie.setDomain("3.34.95.178");
            empCodeCookie.setMaxAge(12 * 60 * 60); // 쿠키의 유효 기간을 12시간으로 설정
            empCodeCookie.setPath("/"); // 쿠키의 경로 설정(모든 경로에서 쿠키 사용 가능)
            response.addCookie(empCodeCookie);
```
### FE서버 쿠키 설정
```
import { createVuestic } from 'vuestic-ui'
import 'vuestic-ui/css'
import './assets/main.css'

import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

import axios from "axios"


axios.defaults.baseURL="http://43.203.123.185:8081/"  //BE Public IP
axios.defaults.withCredentials = true; // withCredentials 전역 설정


const app = createApp(App)
app.config.globalProperties.axios = axios;
app.use(router)


app.use(createVuestic());
app.mount('#app')
```

**Comment by pySatellite** [comment]
크롬 정책 변화에 따라 same-site 설정을 아래와 같이 해보면 어떨까요 ... ( 이미 살펴본걸까요 ^^ )
- https://geondev.github.io/Spring-samesite-option-set/

이 이슈와 별도로 domain 및 https 를 적용 해보는 것도 해보면 좋은 경험이 될거 같아요.
