### ISSUE TITLE
AWS K8S Deploy #1 - 500원 도메인 https 연결 - EC2

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#127]
# 목표
- [ ] 나만의 도메인 보유하기
- [ ] https 인증서 만들어 적용하기
- [ ] https 인증서 적용된 나만의 도메인 AWS EC2 와 연결하기 

# 준비물
- [ ] 500원(VAT 별도)
![LGTM](https://i.lgtm.fun/2qzh.png)
- [x] https://www.gabia.com 회원가입 ( 모두 )
- [ ] 무엇을 살지 팀결정 - gabia.com 에서 검색해 보세요. 구매 가능 도메인 확인 가능합니다.

# 연결 개략 
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/005d3ec0-2b64-4c94-856c-adf225b4deb9)

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/c3c9f409-c196-4a84-a6e7-8ad620f8c8ed)

# ref
- https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/pull/125

# 추가 도전
- github page 에 내 도메인 연결하기
- https://docs.github.com/ko/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
- https://taedonn.tistory.com/22

**Comment by Seull1** [comment]
가비아 회원가입 이슈

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148920003/65b26480-d600-440e-8d7f-5c97e9656ea2)

**Comment by Seull1** [comment]
wns6141.shop

**Comment by Jaelinny** [comment]
- domain: mamelme.shop

**Comment by Afresh2** [comment]
papplan.store

**Comment by INAUGURATE-Ryong** [comment]
bpssystem.store

**Comment by CoffeerLatte** [comment]
- [ ] coffeenlatte.shop

**Comment by dana096** [comment]
idana.store

**Comment by pdh4869** [comment]
dhpark.shop

**Comment by papercrane55123** [comment]
minicrane.store

**Comment by qkralsgml78** [comment]
minhee.shop

**Comment by minu1215** [comment]
umul.site

**Comment by shimguh** [comment]
ghds.shop

**Comment by raheego** [comment]
ranigoh.store

**Comment by choi3179** [comment]
tearinfree.store

**Comment by dhkdtld37** [comment]
limlim.shop
