### ISSUE TITLE
[T4] CORS 관련 질문

### ISSUE THREAD

**Issue by CoffeerLatte** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#128]
- [ ] https://github.com/team4-order/team4-main/issues/48

이슈 첨부 드립니다.

JWT 단일 로그인 -> JWT + Oauth2(+JWT) 인증  로그인으로 기능을 추가하면서 생긴 CORS 문제에 대해서 질문 드립니다.

백엔드에서 계속 디버깅을 해봐야 할지 아니면 프론트에서 CORS를 해결해야 할지 혼동이 되어 질문 드립니다.
> 현재 프론트엔드에서의 CORS 세팅은 (EX. PROXY) 배포 이후에도 생각하고 있기 때문에 없는 상태입니다.

**Comment by pySatellite** [comment]
CorsMvcConfig 에서 .allowedOrigins("http://localhost:8080") 에 FE 쪽을 추가 ... 필요가 있네요.
이렇게 해서 해결 되셨다니 다행입니다.
