### ISSUE TITLE
🌳 🔥 2차 배포 안내 - https 를 적용한 FE, BE 배포 진행 및 코드 리뷰 준비 안내

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#129]
# 확인
- [ ] 모든팀 제출 및 접속 확인
- [ ] [한국만 접속 하용하는 WAF 적용](https://support.bespinglobal.com/ko/support/solutions/articles/73000544860--aws-waf-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%ED%95%B4%EC%99%B8-ip-%EC%B0%A8%EB%8B%A8)

|TEAM|URL|isConnect|
|------|---|---|
|T1|https://bpssystem.store/|X|
|T2|http://35.78.127.23:5174//|X 403 Forbidden|
|T3|https://9-1379.store/|X|
|T4|X/|X|
|T5|https://umul.site/|X|

# https 를 적용한 FE, BE 배포 진행 및 코드 리뷰 준비 안내

- 아래와 같은 형식으로 2차 배포에 대한 결과를 코맨드로 남겨 주시길 부탁드립니다.
- 이를 통해 현 상태 점검 및 코드리뷰 및 스프링 테스트를 추가하는 방법을 공유하며 자바에 대해 추가적으로 보강을 잡도록 하겠습니다.
- 💥 아래 결과물 제출 시 README.md 에 **신경 써 주시길 부탁드립니다.** 해당 문서를 보고 프로젝트를 RUN & DEBUG & TEST 하기에 충분하면 좋겠습니다. 이 문서를 기준으로 **추후에 각각 프로젝트에 테스트를 같이 적용해 보는 출발 문서**로 생각해주세요.

# 결과물 형식
|항목|내용|
|------|---|
|Team Name|-|
|Project Name|-|
|FE URL|-|
|FE 2nd Deployment PR|-|
|BE URL|-|
|FE 2nd Deployment PR|-|

```mermaid
flowchart LR
USER(((USER)))--https-->FE
FE(voting24.shop)--https-->BE(api.voting24.shop)
BE-->DB[(Database)]
```

# 제출은 4월 5일 🌳 금요일 12시 까지 ⭐ 🌈 🔥

**Comment by INAUGURATE-Ryong** [comment]
### [T5]

|항목|내용|
|------|---|
|Team Name| BPS|
|Project Name|의약품 도매 영업 관리 시스템|
|FE URL|https://bpssystem.store|
|FE 2nd Deployment PR|https://github.com/Team5-be01-Final-Project/Backend/pull/2|
|BE URL|13.209.207.115:8081|
|BE 2nd Deployment PR|https://github.com/Team5-be01-Final-Project/Backend/pull/70|

**Comment by pySatellite** [comment]
> ### [T5]
> 항목	내용
> Team Name	BPS
> Project Name	의약품 도매 영업 관리 시스템
> FE URL	https://bpssystem.store

502 가 그렇듯 하게 뜨네요. ^^ 내일 작업 다 되면 기대됩니다. 🌳 🔥

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/f0e1eee8-0676-4a6f-b886-2fffd5300b6f)

**Comment by choi3179** [comment]
## [T2] 

|항목|내용|
|------|---|
|Team Name| Papillon|
|Project Name|효율적인 업무를 위한 일정관리 시스템|
|FE URL|https://papplan.shop/|
|FE 2nd Deployment PR|https://github.com/T2-Papillon/front-vue/pull/88|
|BE URL|http://3.114.241.233/8888|
|BE 2nd Deployment PR|https://github.com/T2-Papillon/Spring/pull/58|

- https 도메인 적용을 추후 진행 예정입니다.

**Comment by papercrane55123** [comment]
## [T1]

|항목|내용|
|------|---|
|Team Name|SSG|
|Project Name|UMUL(우물)|
|FE URL|https://umul.site/|
|FE 2nd Deployment PR|https://github.com/final-kms/main/pull/92|
|BE URL|http://minicrane.store/|
|BE 2nd Deployment PR|https://github.com/final-kms/main/pull/91|

* README.md의 경우 [v2.0.0/Backend Branch](https://github.com/final-kms/main/tree/v2.0.0/backend)에 정리되어 있습니다.

**Comment by ldh0308** [comment]
# 결과물 형식
|항목|내용|
|------|---|
|Team Name| 9-1379 |
|Project Name| 배지를 활용한 인사관리시스템 |
|FE URL| https://9-1379.store |
|FE 2nd Deployment PR| https://github.com/9-1379/T3-R2-FE-Server/pull/35 |
|BE URL| https://9-1379-be.store/ |
|BE 2nd Deployment PR| https://github.com/9-1379/T3-R1-BE-Server/pull/33 |

도메인 연결 후 배포 완료입니다. release v1.0.0

**Comment by CoffeerLatte** [comment]
### [T4]

|항목|내용|
|------|---|
|Team Name| EO |
|Project Name| team4-order |
|FE URL|https://easyoms.store|
|FE 2nd Deployment PR| https://github.com/team4-order/4team_final_MainVue/pull/45 |
|BE URL| |
|BE 2nd Deployment PR| https://github.com/team4-order/4team_final_MainSpring/pull/45 |

## vue - vue-light-bootstrap-dashboard-master 메인 폴더
## spring - demo2 메인 폴더

**Comment by pySatellite** [comment]
# 4팀 배포 완료 되면 아래 jenkins 에서 정적분석 결과를 보면서 코드리뷰 해봅시다

- jenkins.cciiccdd.store

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/45c346ee-f07b-4ca3-9575-b3aec7960d40)

**Comment by ldh0308** [comment]
vpn 우회하여 런던에서 접속시 차단 확인 완료했습니다.
@pySatellite 

- VPN 우회
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/142721325/45f09a57-d2f0-4600-b4e4-35a287b19570)

- 차단확인
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/142721325/a3b5cc8e-4c23-4a86-8717-079ea1689321)
