### ISSUE TITLE
코드리뷰 정리 및 정적분석 적용

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#132]
### 지연된 팀들은 이슈에 대하여 적극적으로 회신 및 질문 부탁드립니다.

- [ ] https://jenkins.cciiccdd.store 모든 개발자 jenkins 가입
- [ ] 샘플 프로젝트 둘러보기
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/77fdd5c6-75a2-43f8-9231-594bd682a2be)

- #129 배포 완료에 따른 각각 branch 해당 이슈 기입
- 팀 조직 레포에 pysatellite 계정 관리자 초대 ( 각팀 형상관리자 )

**Comment by dana096** [comment]
@pySatellite 강사님 조직 레포에 초대하였습니다. 확인 부탁드립니다!

**Comment by pdh4869** [comment]
- [x] https://jenkins.cciiccdd.store/ 모든 개발자 jenkins 가입

- [x] 샘플 프로젝트 둘러보기

**Comment by pdh4869** [comment]
@pySatellite 초대했습니다.

**Comment by yjinlee99** [comment]
@pySatellite 초대했습니다. 확인 부탁드립니다

**Comment by dhkdtld37** [comment]
@pySatellite 강사님 [T5] 레포에 초대 완료했습니다.

**Comment by qkralsgml78** [comment]
@pySatellite T4 조직 레포에 초대 완료했습니다.
