### ISSUE TITLE
최종발표 리허설 및 초록 제출 안내

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#135]
## 초록 제출
- 최종 발표의 개략적인 방향성을 담아 아래 체출 요망
- [x] 최종발표 초록 제출(500자 내외 이미지 3장(FE, BE,Architecture) -> 아래 댓글 4/19 오전 11시 마감

## 리허설
- 아래 일정으로 진행하며, 진행 하면서 순서를 정하도록 하겠습니다
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/40f77ae8-b90a-4f27-a535-d05009667c7f)

**Comment by INAUGURATE-Ryong** [comment]
5팀 최종발표 초록 제출합니다. 
- https://drive.google.com/drive/folders/11X4pnbjAMVXehpkcM8roqQQn8rvDD_r9

**Comment by papercrane55123** [comment]
[T1] 최종 발표 초록 및 (BE, FE, Architecture) 이미지 제출 : [Google Drive T1](https://drive.google.com/drive/folders/1qT26rqFfM8LFAvCFIVPvtuHrIXJmBHN-)

**Comment by Afresh2** [comment]
2팀 최종발표 초록 제출합니다.
- https://drive.google.com/drive/folders/1bV1BIbR-yZm995qfvA2GbMe_1KVI3C0f

**Comment by Jaelinny** [comment]
3팀 최종발표 초록 제출합니다.

- https://drive.google.com/drive/folders/1uGINr7KxRSHn86DIapHGMT60Z6kyn_lH

**Comment by qkralsgml78** [comment]
4팀 초록 제출합니다.
- https://drive.google.com/drive/folders/1KLHLromqT-8i4DYJ1iqhSWTpNCvhapQY
