### ISSUE TITLE
최종발표 hands-on 프린트 준비

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#136]
- 심사자 분들이 직접 데모등 접속 가능한 URL / ID / PASSWD 등을 작성하여 출력 배포

### LIST 
- [x] 1Team
```
- 우리들의 물음표, 우물(UMUL)
- https://umul.umul.site
- test / test
```

- [x] 2Team
```
- 당신의 일정을 위한 강력하고 쉬운 서포터, papplan
- https://papplan.shop/
- test@boogle.com / 1234
```

- [x] 3Team
```
- 게임적 요소를 더한 혁신적인 인사관리 시스템
- https://9-1379.store/
- 관리자 ID: admin PW: 1234 
- 직원 ID: user PW: 1234
```

- [x] 4Team
```
- 한줄 소개 : EO (Easy OMS) 빠르고 쉬운 주문 관리 시스템
- URL : http://easyoms.store/login
- ID/PASS:
  (기업 페이지) BUS01 / qwe123!@#
  (거래처 페이지) CON001 / EOW920
```

- [x] 5Team
```
- 한줄 소개 : 제약회사의 최적의 영업을 위한 영업 관리 시스템
- URL: https://bpssystem.store
- ID/PASS: 1111111111 / 1
```

**Comment by INAUGURATE-Ryong** [comment]
### 5Team

- 한줄 소개 : 제약회사의 최적의 영업을 위한 영업 관리 시스템
- URL : https://bpssystem.store/
- ID/PASS : 1111111111 / 1

**Comment by raheego** [comment]
### 2조
- 당신의 업무를 위한 강력하고 쉬운 서포터, papplan
- URL : https://papplan.shop/
- test@boogle.com / 1234

**Comment by pySatellite** [comment]
> * 1111111111
1이 몇개 인가요? 다른 아이디론 안될까요 ㅎ
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/217c1d4e-feb1-4a49-9f8e-9a0db8dd44c2)

**Comment by ae-chae** [comment]
### 4Team
- 한줄 소개 : EO (Easy OMS) 빠르고 쉬운 주문 관리 시스템
- URL : http://easyoms.store/login
- ID/PASS : 
   (기업 페이지) BUS01 / qwe123!@# 
   (거래처 페이지) CON001 / 1234

**Comment by Jaelinny** [comment]
### 3TEAM

- 게임적 요소를 더한 혁신적인 인사관리 시스템
- https://9-1379.store/
- 관리자 ID: admin PW: 1234 
- 직원 ID: user PW: 1234
