### ISSUE TITLE
AC, TL 회의 참여자 선정

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#18]
AC, TL 이 선정되지 않은 팀의 형상관리 담당자께서는 
팀간 협업을 위해 AC, TL 회의 참가자를 팀회의를 통해 지정 부탁드립니다.

관련 총괄은 5팀의 형상관리자에서 취합하여 코맨트 처리 부탁드립니다.

**Comment by jsmin6330** [comment]
### AC 회의 참여자
1팀: 심규혁
2팀: 우지영
3팀: 이영진
4팀: 김민성
5팀: 박민성

### TL 회의 참여자
1팀: 김민우
2팀: 최원규
3팀: 이동혁
4팀: 전승민
5팀: 정수민

**Comment by pySatellite** [comment]
감사합니다. 해당 이슈 종료합니다.

![LGTM](https://i.lgtm.fun/2pvm.gif)
