### ISSUE TITLE
3/24 AC 회의 결과(통합 ground rule)

### ISSUE THREAD

**Issue by shimguh** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#21]
1. 집중 시간 : "강의실 내에서" 회의 및 대화를 자제하는 시간(필요 시 최대한 조용히)
- 오전 10:00~12:00
- 오후 14:00~16:00
2. AC끼리 매주 ground rule 회의
- 매주 금요일 오후 5시
- 회의 결과를 메인 이슈에 올리기
3. 주간 TL 회의
- 매주 월요일 오후 12시
- 팀 별 상황 진척도를 공유할 수 있는 시간. 이슈 등이 어떻게 해결되었는지 내용 공유.
- 회의 결과를 메인 이슈에 올리기
4. 대형 모니터 예약하는 방법
- 목적 : 팀 내 회의(1시간) / 강사님한테 질문(1시간)
- "1번의 집중 시간" 외 시간에 되도록 진행
- 타임테이블 형식으로 예약 : 구글 캘린더
- https://calendar.google.com/calendar/u/0?cid=OThkN2NlY2JiNDA4MzI1ODE1MzBmMTZiZjQwNmYzYWM1YjQzYjlmNzIyYjhhYWVjMzcxZmNlMzUzZTFkODE5MkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t
- 강사님한테 질문한 내용도 이슈에 올리고, 해결방법도 같이 올리기
5. 다른 팀에게 질문이 있을 시에
- 질문을 받는 팀 PM에게 양해를 구하고 질문하기
- 따로 회의 공간 예약은 안하고, 각자 팀에 가서 질문하기
- 각 팀마다 서로 도움을 요청할 경우 환영해주기
- 전체 이슈에 질문 내용 및 해결한 방법 올리기
6. 건의사항 처리 방법
- 소음 발생 시, 혹은 문제가 있거나 다른 사람에게 할 말이 있을 경우
- 대형 모니터 예약 구글 캘린더에 건의사항 올리기(우선 이렇게 진행해보고 변동사항 필요하면 추가 회의 진행)
* 기타
팀끼리 과자 나눠주기

**Comment by Afresh2** [comment]
![LGTM](https://i.lgtm.fun/2pv5.png)

**Comment by pySatellite** [comment]
https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/15 관련 이슈 중간 파생 이슈로 종료 합니다.
