### ISSUE TITLE
[3/04] Ground Rule 회의 - 변경사항 관련 

### ISSUE THREAD

**Issue by Afresh2** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#31]
## 집중 시간 변경
- 기존 14:00 ~ 16:00 를 15:00 ~ 17:00 로 변경함

## PM, AC, TL 회의 관련 변경사항
- 회의 시간 통일 : 매주 금요일 오후 5시
- 대형 모니터는 TL회의에서 사용
- 기존에 TL이 진행하기로 한 회의(프로젝트 진행 현황 회의)는, 역할 분담 재조정으로 PM이 회의를 진행하기로 함.
- TL회의에서는 각 팀별 기술에 대한 이슈를 공유

## 건의사항 게시판
- 구글 캘린더도 익명성이 보장되지 않으므로,
- 카카오톡 오픈 채팅방(익명으로 참여 권장)을 활용하는 것이 좋을 것 같음

## 회의 관련 이슈 규칙 정하기
- title : [날짜] 회의명 - 주제
- labels : 역할명(AC, TL, PM)과 meeting라벨
- Assignees : 회의 참석자 지정
- 회의 시간에 다음주 회의에 대한 이슈를 만들어 놓고, 건의사항이 올라오면 comment로 올린다.
- 회의 진행 후에 회의결과를 해당 이슈에 comment로 작성

## 질문 관련 이슈 제목 규칙 정하기
- title : [팀명]이슈 내용
- labels : help wanted 라벨

## 통합본
- https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance?tab=readme-ov-file#info

**Comment by pySatellite** [comment]
AC 그룹의 노고에 감사드립니다.

![LGTM](https://i.lgtm.fun/2pyc.gif)

**Comment by Seull1** [comment]
![LGTM](https://i.lgtm.fun/2pb6.png)
