### ISSUE TITLE
프로젝트기획서 초안 작성

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#38]
팀목표 및 개인목표를 담아서
멘토링에 필요한 프로젝트기획서를 만들어 주세요.

# 필요에 집중하여 문서 만들기를 진행하시면 되겠습니다.

최종 완료일은 3/8일 까지 입니다.

- [x] [공용문서함](https://drive.google.com/drive/folders/1neenhFGu6rSoFjx8ahKNsNMV5b78LC92?usp=drive_link) 에 문서를 기록하고
- [x] 초안이 완성되면  아래에 URL 을 붙여주세요 ~

**Comment by INAUGURATE-Ryong** [comment]
## [T5-BPS]
-URL : https://docs.google.com/document/d/1JutpuYJL_yCm8hQWI-VryxhG7xn5n237kbDja1depHw/edit?usp=sharing

**Comment by papercrane55123** [comment]
> * [x]  [공용문서함](https://drive.google.com/drive/folders/1neenhFGu6rSoFjx8ahKNsNMV5b78LC92?usp=drive_link)
> * [x]  URL : https://docs.google.com/document/d/1iWyEFHQGv5IDeYL0uMqJlMeb0HOWt1MYZgsy8J9n1Jo/edit?usp=sharing

**Comment by Jaelinny** [comment]
## [T3]
- [x] https://docs.google.com/document/d/1iOWMejwwOW-jtP4EsVTU24XaNwyk6SDn51Dw8Jyv1xU/edit

**Comment by dana096** [comment]
### [T2]
- [ ] 공용문서함에 문서 기록
- [ ] 초안 URL : https://docs.google.com/document/d/1HPsK3XY-WgVD8-4Kq4evINS1ANwiXmAckhbbq8fnMxQ/edit#heading=h.14mpx6a8znb7

**Comment by qkralsgml78** [comment]
[T4] 

- [x] 공용문서함에 문서 기록
- [x] 초안 URL : https://drive.google.com/drive/folders/15XvKZmqtzH5VJ8TeXDi_vwSLFDoFZcLD

**Comment by pySatellite** [comment]
- [ ] https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/47 통한 작성 사례 및 멘토링 노하우 공유

**Comment by pySatellite** [comment]
초안은 모두 작성하신것으로 파악됩니다.
추후 프로젝트 진행간 업데이트 부탁드리며, 내일 제출 공유 파티에서 1차본을 함께 살펴 보아요.
