### ISSUE TITLE
[PM미팅] 멘토링 후기 & 노하우 및 프로젝트 상황 공유

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#47]
# 안건
- [x] 멘토링 후기 - 앞으로 멘토링을 잘 받기 위한 방안
- [x] 프로젝트 상황 공유 ( 진척 상황 / 문제 상황 / 공유 하고 싶은 것 )
- [x] 기획서 사례 공유

# 일시
- 3월 6일(수) 오후 3시10분 ~ 3시 40분

🌠 사전 공유 내용이 있으시면 코맨트 부탁드립니다.

**Comment by pySatellite** [comment]
# 엑션아이템
- [ ] 매주 PM 정보 공유를 하기로 하였고 다음주는 1조 ( @papercrane55123 ) 님이 일정 잡고 진행 해주기로 하심 - 일정 초대와 함께 해당 이슈는 종료 부탁드립니다.

**Comment by pySatellite** [comment]
1조 PM @papercrane55123 님이 회의 내용 정리해주셔서 공유합니다.

https://github.com/final-kms/main/issues/22

**Comment by pySatellite** [comment]
@papercrane55123 님 해당 이슈의 종료가 지연되고 있습니다. 엑션 아이팀 진행 및 이슈 종료 부탁드려요.

**Comment by papercrane55123** [comment]
죄송합니다. 월요일 멘토링 진행 후 이슈 작업하려다 보니 늦어졌습니다. PM 회의 이슈를 새롭게 올렸으니 해당 이슈는 종료 하도록 하겠습니다. 감사합니다.
