### ISSUE TITLE
[PM] 화면설계서 양식 공유드립니다. 활용하실 팀들은 활용하시면 좋을 것 같아 공유드립니다!

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#53]
- 파일이 PPT 양식인 점 참고 해주세요!
- 파워포인트가 없으신 팀들은 GoogleDrive에 업로드해서 사용하시면 될 것 같습니다!
[화면설계서_모바일웹_v01.pptx](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/files/14518077/_._v01.pptx)

**Comment by raheego** [comment]
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/54056684/8b449efe-7972-43e5-8c10-02274f04c1ab)
최고..

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2pg8.png)
+1

**Comment by pySatellite** [comment]
공유 감사드립니다. 해당 양식에 아래와 같이 변경사항기록을 눈여겨 보시고 다른 산출물에도 적용을 검토 하시면 좋겠습니다.

<img width="966" alt="image" src="https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/e590449a-7b10-47b8-832d-436cc42ff236">

- 추천글 : [요구사항 변경은 예방하기 힘듭니다](https://brunch.co.kr/@kbhpmp/197)
