### ISSUE TITLE
Kick-off pizza party & 기획서 보고회 관련 GM 모임

### ISSUE THREAD

**Issue by Jaelinny** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#54]
- https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/52

> * [x]  각팀 형상관리자 분들과 파티 준비위원회 구성 안내
> * [x]  메뉴 / 시간은 위원회 분들이 결정 안내 부탁드립니다
> * [ ]  [프로젝트기획서 초안 작성 #38](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/38) 완료에 따른 3분 요약을 파티에서 진행 부탁드려요. 먹으면서 자유로운 분위기에서 서로 리뷰 해봐요.
> * [ ]  추가로 각팀원들 소개를 옆사람이 해주는 시간도 마련해 보아요.
> * [ ]  기타 프로그램은 준비위에서 챙겨주세요. 저는 카드를 준비할께요.
> 
> PS : 결과물은 망가져도 팀은 남는 프로젝트가 되길 바랍니다.

- + @pdh4869 @dana096 @qkralsgml78 @dhkdtld37 
- Kick-off pizza party 관련 회의를 12시 30분에 진행할까 하는데 다들 어떠신지 코멘트 부탁 드립니다 :)

**Comment by qkralsgml78** [comment]
전 좋습니당!!!💕

**Comment by dhkdtld37** [comment]
네 확인했습니다. 12시 30분에 뵙겠습니다.

**Comment by dana096** [comment]
저도 좋아요~

**Comment by pdh4869** [comment]
좋습니다

**Comment by Jaelinny** [comment]
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/fa502250-a266-48ca-9d38-fd62175edcb0)

**Comment by pySatellite** [comment]
GM 분들 모두 감사드립니다. #56 이슈를 열어 두고 본 이슈는 종료합니다.
