### ISSUE TITLE
기획서 3분 요약 발표 순서 및 킥오프 공지 🥳🎈

### ISSUE THREAD

**Issue by qkralsgml78** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#56]
## 발표자료

- [x] T1 프로젝트 기획서 -> [링크](https://docs.google.com/presentation/d/1G2EDBaFlSII6Uqhn5Is7fIjxEGfOU8yBMfShXhbX0Lk/edit#slide=id.p)
- [x] T2 프로젝트 기획서 -> [링크](https://drive.google.com/file/d/10k-tfcXa4FvDZTFzwtxzz8owpDhggr5M/view?usp=drive_link)
- [x] T5 프로젝트 기획서 ->[링크](https://docs.google.com/document/d/14ydCPkxF4Ui37WrlQTBx6Izzfz7MLiTvDKk_WpHeFEc/edit)
- [x] T3 프로젝트 기획서 ->[링크](https://docs.google.com/document/d/1G_ah14bPR7WVUPla1bSEaoqHJnFp_1bljpN5TxZ25c8/edit#heading=h.q7fxcwrc0900)
## 추가발표
- [ ] #58 

## 내일 3분 발표 순서임다~~~

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/fa502250-a266-48ca-9d38-fd62175edcb0)

### 1. 팀별로 치킨 1개, 떡볶이 1개 바른치킨에서 메뉴 골라서 comment에 올려주시면 됩니다.

> 양식: [T4] 치킨: 메뉴명, 떡볶이: 메뉴명
> 내일 오전까지 업로드 바람~

### 일시 : 3월 8일 금요일 PM 5:50 ~ 7:00

_Originally posted by @Jaelinny in https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/54#issuecomment-1982300075_

**Comment by pdh4869** [comment]
관리자 지원합니다

**Comment by Jaelinny** [comment]
## 치킨 1개 선택
![스크린샷 2024-03-07 134153](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/676324f8-d8d9-44dc-8fe8-f4bd5460d677)
![스크린샷 2024-03-07 134716](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/cfc180d3-3f24-46a8-9595-6bb8b06045b9) ![스크린샷 2024-03-07 134751](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/4f459b83-2631-4469-9568-70b8432cf607)

## 떡볶이 1개 선택
![스크린샷 2024-03-07 134827](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/a4a71701-586a-4049-8951-e63510d2561e)

## 사이드 1개 선택
![스크린샷 2024-03-07 135101](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/b7bb94cc-690f-4b31-96c0-b751b0c70600)
![스크린샷 2024-03-07 135125](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/06075b07-9204-4f66-a44b-d4cb87edafd0)
![스크린샷 2024-03-07 135150](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/b21d1263-0b25-4a48-ba09-29e3cc9e3b4d)

**Comment by pdh4869** [comment]
1팀 레드치킨/바른치즈떡볶이/모듬감자튀김 입니다.

**Comment by dana096** [comment]
2팀 반반순살치킨 / 바른치즈떡볶이 / 멘보샤 입니다~

**Comment by INAUGURATE-Ryong** [comment]
-  5팀 :  반반순살치킨 / 바른치즈떡볶이 /  바삭똥집튀김 입니다!

**Comment by pdh4869** [comment]
간장

**Comment by pySatellite** [comment]
금일 킥오프 파티 미 참가팀의 기회사 보고 공유회를 별도로 진행하고자 합니다. 3팀, 4팀 형상관리자 분들은 @Jaelinny @qkralsgml78 차주 월요일(11일) 시간을 조율하여 공유 달력에 등록 후 공지(슬랙) 부탁드립니다.
- [ ] 기획서 공유 추가 발표(3팀, 4팀) 진행

**Comment by pySatellite** [comment]
기획서를 시작으로 여러 산출물을 지나 최종 개발 산출물을 만들어 가시는 여정이 시작되었습니다.

- 요구사항의 변경과 추적에 대해서도 고민을 담아 프로젝트를 진행하면 좋겠습니다.
https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/53#issuecomment-1985194378
