### ISSUE TITLE
Spring 재교육 안내~☃️

### ISSUE THREAD

**Issue by Seull1** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#57]
3월18일 정도부터 강사님께서 짧게 spring 교육을 해주신다고합니다~

저희 교육과정이 아닌 강사님 자체적으로 하시는 교육이기 때문에 

배우고 싶거나 잘 모르겠는 spring 교육내용  있으시면 작성해주세요~

ex) jpa, jwt 궁굼합니다

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2q5v.png)

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/27d5c834-b253-4946-a482-405b9fd016fe)

**Comment by ldh0308** [comment]
**요청 강의**
- JWT를 사용하는 이유, 적용하는 방법이 궁금합니다.

**Comment by INAUGURATE-Ryong** [comment]
### T5 요청강의

- 백엔드와 프론트엔드 연결법
- test코드 작성 및 테스트
- restAPI 끼리 데이터 연동 방법
- MSA를 프로젝트에 녹이는 방법
- Security 와 JWT 활용방안, 쓰는 이유 ( 단순 권한을 관리할 경우엔 JWT를 안써도 되는지)

감사합니다.

**Comment by raheego** [comment]
### T2 궁금해요 
- msa 개념과 어떤식으로 사용되는지 궁금
- security 에 대해 좀더 배우고 싶습니다!
- spring boot MVC 실습

감사합니다.
