### ISSUE TITLE
기획서 공유 추가 발표(3팀, 4팀) 진행

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#58]
금일 킥오프 파티 미 참가팀의 기회사 보고 공유회를 별도로 진행하고자 합니다. 3팀, 4팀 형상관리자 분들은 @Jaelinny @qkralsgml78 차주 월요일(11일) 시간을 조율하여 공유 달력에 등록 후 공지(슬랙) 부탁드립니다.

- [x] 추가 발표 일정 수립
- [x] 발표 자료 사전 안내(아래 이슈 댓글 등록)
- [x] 공유달력 등록
- [x] 일정 공유
- [x] 공유 진행

**Comment by pySatellite** [comment]
@qkralsgml78 @Jaelinny 발표를 위한 기획서의 링크 첨부 부탁드립니다.

**Comment by Jaelinny** [comment]
- [x] T3 프로젝트 기획서 ->[링크](https://docs.google.com/document/d/1G_ah14bPR7WVUPla1bSEaoqHJnFp_1bljpN5TxZ25c8/edit#heading=h.q7fxcwrc0900)

**Comment by pySatellite** [comment]
고생하셨습니다. 매주 더 성장하는 모습 보기 좋네요.
