### ISSUE TITLE
[T5] 배포, 테스트 일정을 WBS 에 어떻게 적용하면 좋을까요?

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#61]
강사님 : )
WBS 목차 작성을 1차로 진행했는데, 검토 요청드립니다!

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Playdata/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Playdata/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#0563C1">

WBS   NUMBER | TASK TITLE | TASK OWNER | START DATE | DUE DATE
-- | -- | -- | -- | --
  |   |   |   |  
1 | Project   Conception & Initiation |   |   |  
1.1 | 팀   목표 세우기 | 전체 | 2024-03-04 | 2024-03-04
1.2 | Branch   Strategy 세우기 | 전체 | 2024-03-04 | 2024-03-04
1.3 | 업무환경   협의 및 세팅 | 전체 | 2024-03-04 | 2024-03-04
1.4 | 소주제   정하기 | 전체 | 2024-03-04 | 2024-03-06
1.5 | 기획서   작성 | 전체 | 2024-03-05 | 2024-03-08
1.6 | 요구사항   정의서 작성 | 전체 | 2024-03-05 | 2024-03-13
2 | 설계 |   | - |  
2.1 | 화면설계서 |   | 2024-03-08 | 2024-03-15
2.2 | WBS   작성 |   | 2024-03-11 | 2024-03-13
2.3 | 시스템   아키텍쳐 |   | 2024-03-14 | 2024-03-15
2.4 | DB   설계 |   | 2024-03-15 | 2024-03-18
2.5 | ERD   (Entity-Relationship Diagram) |   | 2024-03-15 | 2024-03-18
3 | BE   개발 |   |   |  
3.1 | 사원   등록 개발 |   | 2024-03-18 | 2024-03-19
3.2 | 권한관리   시스템 개발 |   | 2024-03-18 | 2024-03-19
3.3 | 의약품   상품 관리 개발 |   | 2024-03-18 | 2024-03-19
3.4 | 의약품   단가 관리 개발 |   | 2024-03-21 | 2024-03-22
3.5 | 거래처별   판매 상품 관리 개발 |   | 2024-03-21 | 2024-03-22
3.6 | 재고   관리 개발 |   | 2024-03-21 | 2024-03-22
3.7 | 출고   관리 개발 |   | 2024-03-26 | 2024-03-27
3.8 | 매출   조회 개발 |   | 2024-03-26 | 2024-03-27
3.9 | 인센티브   제도 개발 |   | 2024-03-26 | 2024-03-27
3.10 | 거래처   관리 개발 |   | 2024-03-21 | 2024-03-22
3.11 | 콜드체인   기술 개발 |   | 2024-03-26 | 2024-03-28
3.12 | 알람   서비스 개발 |   | 2024-03-26 | 2024-03-29
4 | FE   개발 |   |   |  
4.1 | 사원   등록 개발 |   | 2024-03-19 | 2024-03-20
4.2 | 권한관리   시스템 개발 |   | 2024-03-19 | 2024-03-20
4.3 | 의약품   상품 관리 개발 |   | 2024-03-19 | 2024-03-20
4.4 | 의약품   단가 관리 개발 |   | 2024-03-22 | 2024-03-25
4.5 | 거래처별   판매 상품 관리 개발 |   | 2024-03-22 | 2024-03-25
4.6 | 재고   관리 개발 |   | 2024-03-22 | 2024-03-25
4.7 | 출고   관리 개발 |   | 2024-03-27 | 2024-03-28
4.8 | 매출   조회 개발 |   | 2024-03-27 | 2024-03-28
4.9 | 인센티브   제도 개발 |   | 2024-03-27 | 2024-03-28
4.10 | 거래처   관리 개발 |   | 2024-03-22 | 2024-03-25
4.11 | 콜드체인   기술 개발 |   | 2024-03-28 | 2024-04-01
4.12 | 알람   서비스 개발 |   | 2024-03-28 | 2024-04-02
4.13 | 대시보드   개발 |   | 2024-03-28 | 2024-04-02
4.14 | 공통화면   개발 |   | 2024-03-28 | 2024-04-02
5 | 테스트 |   |   |  
5.1 | 단위   테스트 시나리오 |   | 2024-03-21 | 2024-04-22
5.2 | 단위   테스트 결과 |   |   |  
5.3 | 통합   테스트 시나리오 |   | 2024-04-04 | 2024-04-05
5.4 | 통합   테스트 결과 |   | 2024-04-04 | 2024-04-05
5.5 | 부하테스트 |   | 2024-04-04 | 2024-04-05
6 | AWS   환경설정 |   |   |  
6.1 | AWS   계정 생성 및 빌링온 연동 |   |   |  
6.2 | IAM   역할 및 사용자 설정 |   |   |  
6.3 | 가상   서버 또는 컨테이너 설정 |   |   |  
7 | CI   / CD 파이프라인 구축 |   |   |  
7.1 | 젠킨스   설치 및 구성 |   |   |  
8 | 배포 |   |   |  
8.1 | jar   - aws 배포 |   |   |  
8.2 | Docker   - aws 배포 |   |   |  
9 | 발표 |   |   |  
9.1 | git   readme 작성 |   |   |  
9.2 | 시연영상   제작 |   |   |  
9.3 | 발표자료   제작 |   |   |  
9.4 | 발표 |   |   |  

</body>

</html>

**Comment by INAUGURATE-Ryong** [comment]
@pySatellite  강사님ㅎ 질문내용 세분화 하여 다시 전달드립니다. 

- AWS 환경설정 부터 배포까지 목차 및 순서가 맞는지 확인 부탁드립니다.
- 젠킨스를 활용하려 하는데 CI/CD 파이프라인 구축은 언제 진행해야 하는지.
- 보통 단위테스트를 진행 할 때, 앞서 진행한 단위테스트를 포함하여 진행하는지, 기능별로 1차, 2차 등 나눠서 진행하는지 궁금합니다.
- 도커는 언제 진행해야하는지

**Comment by pySatellite** [comment]
> @pySatellite 강사님ㅎ 질문내용 세분화 하여 다시 전달드립니다. https://docs.google.com/spreadsheets/d/12YSTL03Vkp5sJB98k0OAiqpQV4MevNZT/edit?usp=sharing&ouid=113970030540133919695&rtpof=true&sd=true
> 

접근권한의 문제가 있습니다. 질문 시 관련 문서는 공용문서함에 넣어 주시면 좋겠습니다. 수정 부탁드립니다.

**Comment by INAUGURATE-Ryong** [comment]
@pySatellite 
https://docs.google.com/spreadsheets/d/1XfXNtEZMaKffnCLEoBIi56B7Pgk0MnQ7/edit#gid=1031195162
공유문서함에 업로드 했습니다!

**Comment by pySatellite** [comment]
@INAUGURATE-Ryong 5시 미팅을 공유달력에 하나 잡아주셔요 ^^

**Comment by pySatellite** [comment]
### 회의를 통해 드린 답변의 요약입니다
- #49 를 통해 AWS 환경과 배포에 대한 이해를 높이고
- 배포의 중점을 생산성에 두고 GITHUB ACTION 도입을 통한 배포 이후 젠킨슨을 고려 하면 좋겠어요.
- 단위 테스트는 ( junit 을 활용한 코드단과 기능테스트라도 부르는 단위*기능 테스트로 분리하여 생각하시면 좋겠어요
