### ISSUE TITLE
[T4] 배송루트 실시간 추적 기술에 관한 질문 및 한도 기능 추가 여부

### ISSUE THREAD

**Issue by qkralsgml78** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#62]
### 1. 여신 현황에 대한 추가 여부
- 여신관리를 통해 한도를 결정 후 한도 초과 시 주문하는 주문 시 결제 페이지로 이동
- 수수료를 적용시키는 기능
### 2. 배송 루트를 실시간으로 보여주는 것이 기술적인 문제를 결정하여 추가 (멘토님, 강사님께 질문)

**Comment by ae-chae** [comment]
출발지, 목적지가 있고 현재 배송 중인 위치를 단말기의 gps 위치를 띄우는 방식으로 사용자에게 시각적으로 표현하고자 함
(경로는 지도에서 오버레이)

1. 카카오맵
- 카카오 내비: app에서만 사용 가능한 것으로 보임. 사용한다면 공기계를 하나 두고 화면을 캡처하여 웹에 띄우는 형식으로 사용
2. 네이버 지도
- 길찾기 기능 사용: 일정 부분 유료..
https://api.ncloud-docs.com/docs/ai-naver-mapsdirections-driving

**Comment by pySatellite** [comment]
네 알겠습니다. 점심 시간 만나요

**Comment by pySatellite** [comment]
# 미팅 후 의견
- [ ] 지도 API 는 구글을 확인하면 더 좋을거 같아요.
- [ ] 지도를 이용한 기능은 본 기능을 만들고 추가적으로 진행하면 좋겠음
- [ ] 해당 기능을 누가 보고 어떤 목적을 갖고 보는지 명확하게 하면 좋겠어요
- [ ] 추가로 질문한 여신/신용 부분은 외부 시스템과 연동이 필요해요. 지금은 연동 하기 어렵다면 관리자 기능을 만들고 / 다만 추후 연동 가능성을 염도하고 API  로 해당 기능을 노출하여 개발하면 더 좋겠네요.
