### ISSUE TITLE
 초집중 업무시간 music playlist 수집 및 운영방안

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#66]
#### 초집중 시간이 마련되면
- https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/pull/65

해당 시간 업무집중도를 높이는 음악을 틀고자함

- [x] 플레이리스트 작성
- [x] 플레이리스트 업데이트 방안
- [x] 플레이리스트 재생 방안
- [x] 담당 DJ 선정

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/c6bbd867-eba2-459d-a068-8fb13d9caa5a)

**Comment by jsmin6330** [comment]
디스코드 하리보봇 추천합니당 🐻
- https://haribosinging.github.io/

**Comment by dhkdtld37** [comment]
유튜브 몽키BGM 재즈 추천합니다 🐵🎹🎵
- https://www.youtube.com/channel/UCBnMxlW70f0SB4ZTJx124lw

**Comment by pySatellite** [comment]
dj 분에게는 클로바스피커 및 네이버 굿즈 제공 예정입니다. 많은 지원 부탁드립니다.

**Comment by INAUGURATE-Ryong** [comment]
- 유튜브 뮤직 알고리즘을 활용하여 진행하면 좋을 것 같습니다.

**Comment by ldh0308** [comment]
DJ 지원합니다

**Comment by pySatellite** [comment]
@ldh0308 님 지원 감사합니다. 관련해서 운영 전권을 휘둘러 ^^ 주시기 바랍니다.
