### ISSUE TITLE
hyper intensive working hours 논의

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#67]
- 시범 운영기간 3월 11일 12 양일간 시행
- [x] 운영 이후 장/단점 논의
- [x] 차후 운영 방안 각팀 AC 협의를 통해 PR 생성

해당 논의에 대한 의장은 @Seull1 4팀 AC 분이 진행 부탁드립니다.

**Comment by Seull1** [comment]
![LGTM](https://i.lgtm.fun/2q6e.png)

**Comment by pySatellite** [comment]
18일 부터 진행 DJ 님에게 굿즈 전달
