### ISSUE TITLE
AWS 세계여행

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#68]
## keywords
- ec2, ssh, scp

## 목표
- 1. 클라우드 서비스인 AWS 의 가상 컴퓨터(VM - EC2) 생성/삭제/중지
- 2. (1)에 접속(ssh)
- 3. (1)에 파일 주고 받기(scp)

- https://aws.amazon.com/ko/about-aws/global-infrastructure/
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/22963ecd-33d2-46f0-b44d-77c17e3b27da)

- https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

  코드 | 이름 | 옵트인 상태
  -- | -- | --
  us-east-2 | 미국 동부(오하이오) | 불필요
  us-east-1 | 미국 동부(버지니아) | 불필요
  us-west-1 | 미국 서부(캘리포니아 북부) | 불필요
  us-west-2 | 미국 서부(오레곤) | 불필요
  af-south-1 | 아프리카(케이프타운) | 필수
  ap-east-1 | 아시아 태평양(홍콩) | 필수
  ap-south-2 | 아시아 태평양(하이데라바드) | 필수
  ap-southeast-3 | 아시아 태평양(자카르타) | 필수
  ap-southeast-4 | 아시아 태평양(멜버른) | 필수
  ap-south-1 | 아시아 태평양(뭄바이) | 불필요
  ap-northeast-3 | 아시아 태평양(오사카) | 불필요
  ap-northeast-2 | 아시아 태평양(서울) | 불필요
  ap-southeast-1 | 아시아 태평양(싱가포르) | 불필요
  ap-southeast-2 | 아시아 태평양(시드니) | 불필요
  ap-northeast-1 | 아시아 태평양(도쿄) | 불필요
  ca-central-1 | 캐나다(중부) | 불필요
  ca-west-1 | 캐나다 서부(캘거리) | 필수
  eu-central-1 | 유럽(프랑크푸르트) | 불필요
  eu-west-1 | 유럽(아일랜드) | 불필요
  eu-west-2 | 유럽(런던) | 불필요
  eu-south-1 | 유럽(밀라노) | 필수
  eu-west-3 | 유럽(파리) | 불필요
  eu-south-2 | 유럽(스페인) | 필수
  eu-north-1 | 유럽(스톡홀름) | 불필요
  eu-central-2 | 유럽(취리히) | 필수
  il-central-1 | 이스라엘(텔아비브) | 필수
  me-south-1 | 중동(바레인) | 필수
  me-central-1 | 중동(UAE) | 필수
  sa-east-1 | 남아메리카(상파울루) | 불필요

# ref
- https://aws.amazon.com/ko/free/
- https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/connect-to-linux-instance.html

**Comment by pySatellite** [comment]
### 요금
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/2d98e9cd-9e41-4f95-a7c5-831431f8ede6)

**Comment by pySatellite** [comment]
# 사용자 생성 완료 확인
- 아래에

**Comment by pySatellite** [comment]
## 리전별 요금
- https://aws.amazon.com/ko/ec2/pricing/on-demand/

**Comment by jsmin6330** [comment]
저는 아래 명령어 입력 시 아래와 같이 코멘트가 뜨는데, 이 차이가 사이트가 열리지 않는 이유 같습니다.
```
python3 - m http.server
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
