### ISSUE TITLE
[PM미팅](일정 변경) 멘토링 후기 & 노하우 및 프로젝트 상황 공유 2주차

### ISSUE THREAD

**Issue by papercrane55123** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#69]
# 변경사항
휴가인 팀이 있어 PM 회의 일정을 변경합니다.
3월 13일(수) 오후 3시10분 ->  3월 14일(목) 오후 3시10분

# 안건
- [x] 멘토링 후기 - 앞으로 멘토링을 잘 받기 위한 방안
- [x] 프로젝트 상황 공유 ( 진척 상황 / 문제 상황 / 공유 하고 싶은 것 )
- [x] 기획서 사례 공유

# 일시 
- 3월 13일(수) 오후 3시10분 ~ 3시 40분

🌠 사전 공유 내용 및 일정 변경 요청이 있으시면 코맨트 부탁드립니다.

**Comment by papercrane55123** [comment]
T1에서 진행한 멘토링 내용이 도움될까하여 이슈 남깁니다.
\* [T1] 1주차 멘토링 정리 : https://github.com/final-kms/main/issues/39
\* [T1] 2주차 멘토링 정리 : https://github.com/final-kms/main/issues/36

**Comment by pySatellite** [comment]
> @papercrane55123 기획서는 어제 발표까지의 발표로 서로 공유가 되었다고 생각하는데 혹시 기획서 사례 공유가 발표 이외에 내용들을 공유하는건가요~?

각 팀마다 자랑하고 싶은거 하면 되겠죠 ^^

**Comment by pySatellite** [comment]
앞으로 많이 바쁘겠지만 서로 시간을 만들어 상호 함께 성장하는 프로젝트 문화 만들어 가길 부탁드립니다. 화이팅!!!
