### ISSUE TITLE
[T2] 시스템 아키텍처 1차 수정 검토 요청드립니다.

### ISSUE THREAD

**Issue by choi3179** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#70]
- 시스템 아키텍처 작업 중에 우선 개발환경에 대하여 작성해 보았습니다.
- 하나의 EC2 에 도커환경으로 관련 스택을 모두 넣어 보았는데요.
- 문제가 없을지 검토 부탁드립니다.
- 이렇게 구성한 이유는 도커 컴포즈로 로컬 환경에서도 똑같이 구성했다가 바로 AWS 에 배포하기 위함 입니다.
- 향후 STG PRD 로 가면 EC2 인스턴스를 분리할 계획입니다.

- https://github.com/T2-Papillon/Main/issues/4#issuecomment-1987855161

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/ae25ac13-3acf-48db-8e29-2d8abb7a28d7)

**Comment by pySatellite** [comment]
# 의견
- [예시](https://docs.google.com/presentation/d/1ndVLN4eNXUkMJZXI6_jfBzbM0yQ8mxckQ-Dcvc7c1qM/edit#slide=id.p) 와 같이 공동 편집 가능한 파일이면 좋겠어요.
- nginx 블럭은 캐싱을 위한것인가요? 캐싱이나 정적파일을 톰켓보다 효율적으로 사용가능해서 저렇게 위치는 시키지만 개발존에서는 필요 없을거 같아요. STG PRD 아키텍처를 따로 만들때 적용하면 좋겠습니다.

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/c995cede-74bd-477f-b5be-07ceed1b3ca3)
