### ISSUE TITLE
[T5] 요구사항 정의서 및 요구사항 제안서 제출 

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#78]
요구사항 정의서 및 제안서 공유폴더에 업로드 했습니다.
저희팀은 요구사항정의서를 마인드맵 형식으로 간단하게 작성 하였습니다.
우선은 사용자별로 작성했지만, 멘토님께서 기술별로 나뉘는게 좋다고 하여 기술적으로 다시 작성하였고, 
그 마인드맵을 바탕으로 기술정리 후 요구사항 제안서 작성을 진행하였습니다.

- https://drive.google.com/drive/folders/1wx9vT6l39fkstvRns7SPsiefGw4d-ZGy

**Comment by pySatellite** [comment]
- 문서함에 버전별 문서가 기록되어 좋습니다.
- 문서에 버전 추적 사항 기입도 아주 좋아요.
- 요구사항ID 를 통해 추후 개발 및 부가 산출물의 추적을 하면 좋겠어요. ID 를 빈칸으로 남겨두진 않을실꺼죠?
- 예를 들면 ID 를 브랜치이름 등으로 사용해서 추적하는 것도 좋아 보입니다. 또는 Milestone 과 연결해서 추적하는 방법도 있겠습니다.

**Comment by INAUGURATE-Ryong** [comment]
@pySatellite 
감사합니다 강사님. 
요구사항 ID는 개발 시작전에 브랜치나 WBS넘버링 활용하여 작성해 추적하는 방향으로 진행하도록 하겠습니다.
