### ISSUE TITLE
[T3] 요구사항 정의서 제출

### ISSUE THREAD

**Issue by ldh0308** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#79]
요구사항 정의서 공유폴더에 업로드 했습니다.

- https://drive.google.com/drive/folders/1woZykGvelHSJKXGjCJfNd4LUHQt_tdqH

**Comment by pySatellite** [comment]
- 폴더에 이름이 다른 문서 2개가 있어요. 어떤것이 진짜 일까요? ^^
- 그리고 버전 및 변경사항 기록 하신 부분이 좋아 보입니다. 차후 요구사항별로 이슈나 PR 을 만들때 해당 작업코드가 요구사항 항목별로 관리되는 방안을 고민해 보시면 좋겠습니다.(추적관리 위해)

**Comment by Jaelinny** [comment]
> * 폴더에 이름이 다른 문서 2개가 있어요. 어떤것이 진짜 일까요? ^^
> * 그리고 버전 및 변경사항 기록 하신 부분이 좋아 보입니다. 차후 요구사항별로 이슈나 PR 을 만들때 해당 작업코드가 요구사항 항목별로 관리되는 방안을 고민해 보시면 좋겠습니다.(추적관리 위해)

: 저희팀은 요구사항 정의서를 완성한 후 요구사항 명세서까지 추가로 작성해서 폴더에 2개를 함께 넣어 놨었는데, 현재 요구사항명세서 폴더를 따로 만들어 두었습니다 ! 두개 모두 참고해주시면 좋을 것 같습니다 :)
