### ISSUE TITLE
[T4] 요구사항 정의서 제출   ~~~~

### ISSUE THREAD

**Issue by Seull1** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#80]
요구사항 정의서 공유 폴더에 업로드 했습니다.

- https://drive.google.com/drive/folders/1IJt9EgxLINyGGdo4zeXbdm4qndyo8aJt

**Comment by pySatellite** [comment]
Milestone 도 잘 지정해 주셨네요 ^^
