### ISSUE TITLE
[T5] WBS 전달드립니다.

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#83]
- v1은 큰 개발틀로만 일정을 매핑하여 진행했지만, 멘토링 이후 멘토님께서 세부적으로 기술을 나눠 작성하는게 좋다고 하여 v2에는 기술별 세부적으로 나눠 매핑을 진행했습니다.
- 담당자 지정은 그 담당자만 기술개발을 진행하는게 아닌, 주로 담당자가 진행하지만 도움을 요청 시 담당자들의 주도하에 업무분장을 하도록 하였습니다. 
- 개발을 진행하면서 일정은 조율 및 조정하면서 진행할 예정입니다.
- 현재 WBS 넘버링과 요구사항ID, 브랜치를 통일할 지에 관해서는 GM님께서 고민 후 공유 주시기로 하셨습니다.

- https://docs.google.com/spreadsheets/d/1GojRru23LcbJ01EYxQBS7ewtyuri-9vb/edit#gid=1031195162

**Comment by pySatellite** [comment]
<img width="245" alt="image" src="https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/8ea7d20b-0c0b-4605-a87a-7e594f9b606f">

버전 관리 및 탭으로 이전 버전 문서를 남겨 두니 추적성이 좋아지네요. 꿀팁입니다.
