### ISSUE TITLE
[T2] 요구사항명세서 제출합니다.

### ISSUE THREAD

**Issue by raheego** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#84]
안녕하세요 선생님
T2 요구사항명세서 팀공유 드라이브에 업로드 완료하였습니다.
확인부탁드립니다.

### 링크첨부
- **파일명** : [[T2] 요구사항명세서_v0.4.1](https://docs.google.com/spreadsheets/d/1857bzS5RYRmDIZrSUV-l5hghgS_H7NzL/edit?usp=drive_web&ouid=109224360927621806756&rtpof=true)(240314)

### 추가 예정
현재 문서에는 요구사항ID 부분이 기입 되어있지 않습니다. 추후 기입할 예정입니다. 참고 부탁드립니다.
또한 타팀 요구사항기획서 코멘트에서 남겨주신 이슈, 마일드스톤 연결하여 추적하는 방향도 고려하겠습니다.

**Comment by pySatellite** [comment]
멘토님이 신경을 많이 써주셔서 현업에 버금가는 형식이 된거 같습니다. 다른 팀들도 많이 봐주시면 좋겠어요.
