### ISSUE TITLE
[T3]WBS 초안 수립 및 제출 

### ISSUE THREAD

**Issue by ldh0308** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#85]
**T3 WBS 일정에 따른 초안 수립 후 해당 산출물(wbs v2) 링크로 제출 합니다.**
:  [WBS_링크](https://docs.google.com/spreadsheets/d/1pf0dYTRBMZZiG69ZnqBES1jNkIrU0ihq0N7LiKFU7Bk/edit#gid=1586591649)

- WBS는 기능에 따른 번호로 분류하여, 기능의 고유성을 부각시켰습니다. 
- 총 2회 개발을 중점으로 일정을 계획하고 있으며, 현재 1차 개발(wbs v2) 목표로 한 wbs 제출 합니다.
- 일정에 비어있는 부분은 현재 협의 중에 있습니다. 

**Q1**
- 기능에 분류번호를 기입하였는데 해당 번호로 branch 생성해서 기능 작업을 해도 되는지 궁금합니다.

**Comment by pySatellite** [comment]
### 질문
- 분류번호를 기입하였는데 해당 번호로 branch 생성해서 기능 작업을 해도 되는지 궁금

### 답
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/6b1df055-b57f-4e27-82a1-9f90cf9a4c9b)

@ldh0308 링크는 어디 있나요?

**Comment by Jaelinny** [comment]
> ### 질문
> * 분류번호를 기입하였는데 해당 번호로 branch 생성해서 기능 작업을 해도 되는지 궁금
> 
> ### 답
> ![image](https://private-user-images.githubusercontent.com/87309910/313077849-6b1df055-b57f-4e27-82a1-9f90cf9a4c9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODA5NjQsIm5iZiI6MTcxMDQ4MDY2NCwicGF0aCI6Ii84NzMwOTkxMC8zMTMwNzc4NDktNmIxZGYwNTUtYjU3Zi00ZTI3LTgyYTEtOWY5MGNmOWE0YzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA1MzEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZDM1NmI0NmY2MjU4NDI3YWVkMGJlNDA0ZTJjYTQ3MGNlN2I4ZjFlNDY4ODFmYTlkYTlmZTdhZTY5ODRjMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KD-nRgroT08oJxwS_Nzrk1etcePwDkq2TZr9QdfEGYQ)
> 
> ### 그리고
> @ldh0308 링크는 어디 있나요?

: 죄송합니다. 링크 생성 완료했습니다. 확인 부탁드립니다 !

**Comment by pySatellite** [comment]
굿 좋아요 ^^
