### ISSUE TITLE
[T4] WBS 제출합니다!

### ISSUE THREAD

**Issue by qkralsgml78** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#86]
WBS 공유 폴더에 업로드 했습니다.
- https://docs.google.com/spreadsheets/d/1IHHPTzakxlUNngsBwD1AC_1VntL8eHs20aSuk2fAiDc/edit#gid=1494354869

**Comment by pySatellite** [comment]
# 두둥 !
이제 시작이네요. 달려 보아요.

<img width="916" alt="image" src="https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/5265c42c-f7b3-404d-9b7a-3a299e024cb6">
