### ISSUE TITLE
[3/14] AC 회의 - 초집중시간 운영

### ISSUE THREAD

**Issue by Seull1** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#87]
회의 내용

초집중시간
- 기존 방식대로 16:00~17:00 1시간 진행
- 3/18~3/21 기존 방식대로 진행 후 정기 회의 시간에 의견 논의
- 영어 또는 가사 없는 노래로 진행( 노래 건의 사항은 DJ 동혁님에게 오픈카톡방으로 문의)

정기회의
- 매주 금요일 17:00 PM, AC TL, GM 회의 진행
- GM 회의 : git 관리하면서 좋은점 아쉬운점 문제해결한 사례들 공유
- 부재로 인해 회의 진행이 어려울 경우 다른 날짜를 잡거나 다른 팀들과 의견 조율

**Comment by Seull1** [comment]
각 팀들의 초집중시간 의견 모아주시면 좋을것 같습니다.

**Comment by Afresh2** [comment]
2팀은 오후 5시에 멘토링으로 조퇴해야 되서, PM회의 끝나는 대로 AC회의 가능하실까요...?

**Comment by Seull1** [comment]
저희 팀은 가능할것 같습니다.. 다른팀들은 PM회의직후 AC회의에 대해 어떻게 생각하시나요?

**Comment by shimguh** [comment]
저희도 괜찮습니다

**Comment by Jaelinny** [comment]
3팀은 AC담당 영진님이 조퇴하신 관계로 GM이 대신 참석 할 예정입니다.

**Comment by Afresh2** [comment]
넵 다들 배려해주셔서 감사합니다!

**Comment by Seull1** [comment]
금일 AC 회의 16:05분에 진행하도록 하겠습니다~

감사합니다

**Comment by Afresh2** [comment]
[초집중시간 회의]

(의견)
- 3/18 부터 초집중시간 운영하면 좋겠다
- 집중시간을 삭제하고, 초집중시간을 오후 1시간(4시~5시) 진행하자는 의견
- 개발 시작하고 나서도 대화할 일이 많을 것 같기 때문

- 개발 기간에 4일정도(3/18~3/21) 위와 같이 진행해본 뒤에, 초집중시간을 더 늘리고 싶다는 의견이 생기면
회의를 하면 좋겠다 -> 3/22(금) AC회의 때 의견 논의

(노래)
- 너무 조용해서 음악 트는게 좋겠다
- 가사 없는 노래로 하면 좋겠다(영어 또는 가사 없는 노래)
- DJ 동혁님 : 노래 관련해서는 DJ님께 문의하는걸로(오픈카톡방 많이 활용해주세요... :))


(정기회의 관련)
- 금요일 오후5시 동일시간에 PM회의, AC회의, TL회의 진행 관련
- 결석하는 인원에 대해 동시 회의가 진행이 어려울 수가 있음
- 개발할 시간이 부족한데 회의까지 하기에 시간이 부족하다 
- 하지만 팀별로 진행사항 공유가 필요하다 생각됨
-> 그래서 정기 회의 기존처럼 진행하기로 함
-> 부재는 어쩔수 없음....

- AC회의는 오늘 회의로 대신함!

(건의사항)
- GM회의도 진행을 희망함 -> 금요일 오후5시
- 각 팀별 브랜치 전략, git 관리하면서 좋은점 아쉬운점 문제해결한 사례들 공유하고 싶음

**Comment by pySatellite** [comment]
바쁜시간 쪼개어 모두를 위해 힘써 주셔서 감사합니다.

**Comment by pySatellite** [comment]
달력에 추가했습니다.

@ldh0308 DJ 감사합니다.

<img width="1391" alt="image" src="https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/91a29187-279f-4b72-ad1a-3d4e38a97e47">
