### ISSUE TITLE
[한빛미디어_MSA_세미나_240307] 발표자료 공유

### ISSUE THREAD

**Issue by Jaelinny** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#88]
### 3/7일에 진행되었던 "한빛미디어_MSA_세미나" 발표자료 공유합니다.
- https://festa.io/events/4720
- [MSA_발표자료_pdf](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/files/14598051/HBN_.-.-.-.-.pdf)

<img src="https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/eb43d3ab-18a7-4e28-97e7-c22b47621aa0)" width="700px">

**Comment by raheego** [comment]
![LGTM](https://i.lgtm.fun/2pz1.png)
감사합니다!

**Comment by dana096** [comment]
감사합니당!!

**Comment by pySatellite** [comment]
https://www.hanbitn.com/product/when-the-server/
위 링크 가입 및 0원 수강 가능하네요. pdf 도 받을 수 있으니 다들 가입해서 받아서 보셔요. 영상도 올라 온답니다.
본문 pdf 는 삭제 ! 하겠습니다. 저적권법에 따라 무단 전재를 하지 말라고 써있어요 ^^ 가입하는 김에 영상도 볼 수 있으니 좋네요.
