### ISSUE TITLE
[T2] WBS 제출합니다.

### ISSUE THREAD

**Issue by raheego** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#89]
안녕하세요 선생님
공유 드라이브에 업로드 완료하였습니다.
확인부탁드립니다.

### 링크첨부
- **파일명** : [[T2] WBS_v0.3.0](https://docs.google.com/spreadsheets/d/1XuEmOqaPn7segOZGlVm6nxxUM54dyeHW/edit#gid=1978547635) (240314)

### 업데이트 예정
- 담당자 추가
각 기능별 담당자를 지정하여 기입할 예정입니다.
- 테스트 주요업무
2차 멘토링 후 피드백 사항을 적용할 예정입니다. 
- 지속적인 wbs 업데이트
위 문서는 추후 수정변경될 수 있다는 점 참고부탁드립니다.

**Comment by raheego** [comment]
[T2] WBS 내용 추가하여 업데이트 했습니다. 
참고부탁드립니다.  

### 링크첨부
[[T2] WBS_v0.4.2](https://docs.google.com/spreadsheets/d/10HXRMmvgvw2YoaishMT4gK8Laz3EdN80/edit#gid=664654059) (240315)

### 변경사항
- 기능세분화 기입
- 요구사항명세서 ID 기입

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2qcz.png)
