### ISSUE TITLE
[T4] 인프라 구성 질문

### ISSUE THREAD

**Issue by CoffeerLatte** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#91]
AWS 인프라 구성 관련 질문드립니다~
저희 4팀은 인프라 구성 시 각 어플리케이션을 각각 다른 vm에 띄워놓을 예정입니다.
멘토님과 상의 결과 한화에서도 비슷한 인프라 구성이 형성되어 있다고 말씀해 주셨는데, 자세한 사항은 강사님께 여쭤보는 것이 더 도움이 될 수 있을 것이라 조언 해주셨습니다. 해당 내용 관련해서 강사님 의견을 듣고자 15일(금) 오전 11시~12시에 질문을 요청드립니다.

시스템 구성도 첨부드립니다.
![System Architecture drawio](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/125641153/3fe05a3c-fb06-4d2e-be97-aec8ba414daa)

**Comment by pySatellite** [comment]
네 달력 등록 후 불러주세요 ^^

**Comment by pySatellite** [comment]
오늘 회의 시 검토 의견 드렸습니다. 요약하면
- 간결하고 하나의 목적에 집중하는 문서이면 좋겠음 - ( 스택 / 배포다이어그램 ) 이 섞여 있는 형태에서 배포에 중점을 두고 과감하게 생략하면 더 보기 좋은 문서다 되겠어요.
- 보기 좋은 문서란 ? 개발시 배포 나 접속 구조를 파악하기 좋은 문서
