### ISSUE TITLE
[T1] WBS, 화면 설계서 제출의 건

### ISSUE THREAD

**Issue by papercrane55123** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#92]
[T1 산출물 공유문서함](https://drive.google.com/drive/folders/1GjxP4hPxqbfHuPQyD_W3D3UjNp4AuHFa)
- [x] WBS
- [x] 화면 설계서

T1 WBS 및 화면 설계서 제출합니다. 

### WBS
WBS의 경우 현재 까지의 진행 및 이후 확정된 진행 사항은 정상 기입하였습니다.
백엔드, 프론트엔드의 경우 코드 진행 속도에 따라 일정이 달라질 수 있어 빈칸으로 남겨두었습니다.
위 부분은 매일마다 일정 입력해 가며 버저닝 관리하도록 하겠습니다.

### 화면 설계서
멘토님께서 요청하신 description 디테일(구체성)을 살리고자 이용자 관점에서 사용하기 편리하도록 작성했습니다. 
제출까지 3번의 작은 변경(카테고리 추가, description 수정 등)이 있었기에 금일 제출 버전은 v0.1.2 입니다.

감사합니다.

**Comment by pySatellite** [comment]
산출물의 이용목적에 항시 부합 하는지 견지 하면서 문서를 만들고 수정해 가면 효과적으로 개발 절차에 대해 터특 가능하다 생각됩니다. 문서 내용은 좋고요 수고하셨습니다.

멘토님에게 늘 감사한 마음으로 임해 주세요. 어제 회식은 어떠했나요. 월요일에 들려주세요.
