### ISSUE TITLE
[T3]화면설계 초안 수립 및 제출

### ISSUE THREAD

**Issue by hyunsungJoo** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#93]
**T3 화면설계 초안 수립 후 해당 산출물(v1) 링크로 제출 합니다.**

- 현재 WBS 기능들 기반으로 화면설계 진행하였습니다. 
- 차후 진행하면서 수정 할 예정이며, 수정 분에 대해서는 버전관리 진행하도록 하겠습니다. 

### 링크첨부
[화면설계서_링크](https://docs.google.com/presentation/d/1wtXD1n6xrmsjdoGUUyaHr0Y0WLAK9B3LoFG86p5gUBQ/edit?usp=sharing)

**Comment by pySatellite** [comment]
문서에 접근권한이 ... 없어요 T T
차후 멘토님이나 심사위원들과 공유를 위해 버전관리된 제출 단계 문서는 공용문서함에 넣어주세요 ^^

@hyunsungJoo

**Comment by Jaelinny** [comment]
> 문서에 접근권한이 ... 없어요 T T 차후 멘토님이나 심사위원들과 공유를 위해 버전관리된 제출 단계 문서는 공용문서함에 넣어주세요 ^^
> 
> @hyunsungJoo

: 죄송합니다. ㅜㅜ 링크 수정했습니다. 확인 부탁드립니다 !

**Comment by pySatellite** [comment]
좋아요 ^^

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/c10a0af4-ffaa-479d-bf5e-79238ad314b9)
