### ISSUE TITLE
[T3] 시스템 아키텍처 제출합니다.

### ISSUE THREAD

**Issue by Jaelinny** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#94]
### [T3] 시스템 아키텍처 초안 산출물(v1) 링크로 제출 합니다.
- [T3_시스템 아키텍처 링크](https://app.diagrams.net/#G1ZsXN8uiUohegzMqyV6sLwjGNtlsgZ6o9#%7B%22pageId%22%3A%22aaaa8250-4180-3840-79b5-4cada1eebb92%22%7D)
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/148875683/513cad13-9f36-46ba-bf81-c0c72b81288b)

: 차후 진행 하면서 계속 업데이트 예정입니다.
: 업데이트 된 내용은 변경사항 및 버전을 기록하여 관리 할 예정입니다.

**Comment by pySatellite** [comment]
@Jaelinny 문서에 접근권한이 ... 없어요 T T
차후 멘토님이나 심사위원들과 공유를 위해 버전관리된 제출 단계 문서는 공용문서함에 넣어주세요 ^^

**Comment by Jaelinny** [comment]
> @Jaelinny 문서에 접근권한이 ... 없어요 T T 차후 멘토님이나 심사위원들과 공유를 위해 버전관리된 제출 단계 문서는 공용문서함에 넣어주세요 ^^

: 죄송합니다 ㅜㅜ 링크 수정했습니다. 확인 부탁드립니다.

**Comment by pySatellite** [comment]
버전별 관리 좋아요 ^^
