### ISSUE TITLE
[T2] 화면설계서 제출합니다.

### ISSUE THREAD

**Issue by raheego** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#95]
공유 드라이브에 업로드 완료하였습니다.
확인 부탁드립니다.

### 링크 
- [[T2] 화면 설계서_v2.pdf](https://drive.google.com/drive/folders/1hIuw1HeaFUF8rBgUqUllVU-_kV5-y5ER)

위 문서는 추후 수정 변경될 수 있다는 점 참고 부탁드립니다.

**Comment by pySatellite** [comment]
예상 결과물 까지 넣어 주셔서 참 좋네요. 기대가 됩니다.

<img width="732" alt="image" src="https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/71b1bf17-3ac9-4044-ba42-32a87426e7c6">
