### ISSUE TITLE
[T3] WSL - Intellij 환경설정 공유 

### ISSUE THREAD

**Issue by ldh0308** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#96]
안녕하세요 T3 TL 이동혁입니다.

저희 팀 프로젝트 환경 설정 중 필요하신 분이 계실까해서 이슈 생성하였습니다. 

- intellij를 통한 spring 프로젝트를 linux에 설치하면서 메모리가 부족하다고 경고창이 발생하여 메모리 증가 방법 공유드립니다.
 
- WSL 자체에 메모리가 4gb로 설정 되어 있으신 분들은 아래의 방법을 통해 메모리를 증가 시킬 수 있습니다. 

1. 시작프로그램 -> 실행 -> %userprofile%
2. .wslconfig 파일로 생성하여 아래의 내용 기입
```
[wsl2]
processors=8
memory=8GB   
```
3. 저장 후 WSL 재시작 
4. `$ htop` 을 통해 메모리 증가 확인

- 가이드 링크 공유 : https://learn.microsoft.com/ko-kr/windows/wsl/wsl-config

이상으로 추가적으로 성능향상을 위한 방법 있으시면 공유 부탁드립니다.

**Comment by qkralsgml78** [comment]
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/149050285/aa8db383-35c9-4b3e-85d4-9d9f8778a295)

**Comment by pySatellite** [comment]
감사합니다. 우분투데스크탑으로 갈아타신 이야기도 기대해봅니다 ^^
