### ISSUE TITLE
[T4] 화면 설계서 제출합니다.

### ISSUE THREAD

**Issue by ae-chae** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#97]
- 공유문서함에 0.2.0 버전 업로드 했습니다~ ૮ • ﻌ -ა ♥

https://docs.google.com/presentation/d/1WaXknRRsR4gXmlLyeAglZ9uuLQ69kd8Y7xAHvxIVimE/edit#slide=id.p

**Comment by qkralsgml78** [comment]
![LGTM](https://i.lgtm.fun/2q5j.gif)

**Comment by Seull1** [comment]
![LGTM](https://i.lgtm.fun/1cvq.gif)

**Comment by pySatellite** [comment]
많은 사연이 담겨 있네요. 화이팅 입니다.

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/d24b740c-60f7-4fb1-abf5-21475f50b626)
