### ISSUE TITLE
[T3] ec2에서 mariadb를 직접 실행해서 접속하는 방법

### ISSUE THREAD

**Issue by ldh0308** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#98]
ec2에서 mariadb를 직접 실행해서 접속하고 싶은데 포트를 열어놨음에도 불구하고 접속이 되지 않는 문제에 대해 질문함

- 방법
-  [ ] 포트가 정말 열려있는지 확인 (python web server 사용)
-  [ ] root 는 localhost만 사용가능하기 때문에 권한 변경

**Comment by pySatellite** [comment]
- [MariaDB 원격 접속 허용하기](https://ilimes.github.io/mariadb/post28/) 라고 검색 해보면 많은 답이 있습니다. 다만 버전별로 설정이 조금씩 다른 부분이 있어서 지금 설치하신 버전을 고려하여 보시면 좋아요. 

- 그래서 이런 기술공유 문서를 만들때는 설치환경(설치 버전, OS 버전 ... ) 을 함께 기입하시는 것이 좋아요.

- 도커를 사용하지 않고 ( 도커는 사용 편의성을 우선하여 외부접속이 기본으로 열려있지만) 더 어려운 엔지니어링 길을 택하셔서 좋아요. !!! 결과 기대 하겠습니다.

**Comment by ldh0308** [comment]
답변 감사합니다 강사님! TL 회의 결과 같은 아키텍처로 진행하면 좋을 것 같다는 의견이 나왔습니다. 

말씀해주신부분에 대해서는 별도로 공부할 수 있도록 하겠습니다. 

좋은 결과 낼 수 있도록 노력하겠습니다. 감사합니다.
