### ISSUE TITLE
[GM] (03/15) Git Flow 및 Branch Strategy 공유

### ISSUE THREAD

**Issue by dhkdtld37** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#99]
## 1차 GM 정기 회의

- 앞으로 진행될 프로젝트의 원활한 git 관리를 위해 브런치와 레포 명명 방법 공유
- 배포를 위한 주 브랜치와 기능을 위한 서브 브랜치의 세분화로 충돌 예방
- 커밋 컨벤션 태그 종류의 세분화로 가독성 증가
- PR 생성 후 머지 과정에서 코드 통합 충돌 방지를 위해 관리는 1명 혹은 GM이 담당
- PR 혼란을 방지하기 위한 레포 설정에서 브랜치에 브랜치 보안을 위한 규칙 생성 > 확실히 검증되지 않아 테스트 필요 !
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/149128094/93ad7802-086f-46aa-b2e1-2c5b11eea849)

### 참고 주소
- 브랜치 전략  : https://github.com/9-1379/T3-R0-Document/wiki/9%E2%80%901379-%5B%EA%B7%9C%EC%B9%99%5D-Git-%EA%B4%80%EB%A0%A8-%EA%B7%9C%EC%B9%99
- 브랜치 전략 2 : https://github.com/Team5-be01-Final-Project/.github/wiki/%5B-%EA%B7%9C-%EC%B9%99-%5D-Git-Flow-&-Branch-Strategy
- 브랜치 전략 3 : https://github.com/beyond-sw-camp/be02-fin-BuildUp-KMS/issues?page=4&q=is%3Aissue+is%3Aclosed

**Comment by pySatellite** [comment]
좋은 정보 공유 감사드립니다.

![LGTM](https://i.lgtm.fun/2qg8.png)
